import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Comment",
    description: "Generated by create next app",
};

export default function CommentLayout({
                                          children,
                                      }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <>
            {children}
        </>

    );
}