import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Posts",
    description: "Generated by create next app",
};

export default function PostsLayout({
                                        children,
                                    }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>

            {children}

        </>

    );
}