import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Comments",
    description: "Generated by create next app",
};

export default function CommentsLayout({
                                           children,
                                       }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {children}
        </>

    );
}